### ISSUE TITLE
Boolean column type causes a fatal error

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#277]
```
[20-Jul-2018 05:20:43 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function filter_validate() in E:\work\projects\webdesign\wordpress4.8\wp-content\plugins\visualizer\classes\Visualizer\Source.php:211
Stack trace:
#0 E:\work\projects\webdesign\wordpress4.8\wp-content\plugins\visualizer\classes\Visualizer\Source\Csv.php(139): Visualizer_Source->_normalizeData(Array)
#1 E:\work\projects\webdesign\wordpress4.8\wp-content\plugins\visualizer\classes\Visualizer\Module\Chart.php(496): Visualizer_Source_Csv->fetch()
#2 E:\work\projects\webdesign\wordpress4.8\wp-includes\class-wp-hook.php(298): Visualizer_Module_Chart->uploadData('')
#3 E:\work\projects\webdesign\wordpress4.8\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 E:\work\projects\webdesign\wordpress4.8\wp-includes\plugin.php(453): WP_Hook->do_action(Array)
#5 E:\work\projects\webdesign\wordpress4.8\wp-admin\admin-ajax.php(91): do_action('wp_ajax_visuali...')
#6 {main}
```

**Comment by rodica-andronache** [comment]
@contactashish13 shouldn't this be changed in test-import.php and test-revisions.php too?

**Comment by contactashish13** [comment]
@rodica-andronache I'm not sure what you mean. This was a problem in how we treat booleans.
