### ISSUE TITLE
ftp_nlist() warnings

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/visualizer#598]
https://wordpress.org/support/topic/ftp_nlist-warnings/

**Comment by contactashish13** [comment]
Unable to reproduce this by setting `define('FS_METHOD', 'ftpext');` instead run into another "error" that is probably not an error...

`
Fatal error: Uncaught Error: Call to undefined function ftp_nlist() in E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-ftpext.php:402 Stack trace: #0 E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-base.php(222): WP_Filesystem_FTPext->exists('/work/projects/...') #1 E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-base.php(73): WP_Filesystem_Base->find_folder('/work/projects/...') #2 E:\work\projects\webdesign\wordpress-themeisle\wp-content\plugins\visualizer\classes\Visualizer\Module.php(474): WP_Filesystem_Base->wp_content_dir() #3 E:\work\projects\webdesign\wordpress-themeisle\wp-content\plugins\visualizer\classes\Visualizer\Module\Frontend.php(181): Visualizer_Module->get_user_customization_js() #4 E:\work\projects\webdesign\wordpress-themeisle\wp-includes\class-wp-hook.php(288): Visualizer_Module_Frontend->enqueueScripts('') #5 E:\work\projects\webdesign\wordpress-themeisle\wp-includes\class-wp-hook.php(312): in E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-ftpext.php on line 402
`

any string value of `FS_METHOD` except `direct` causes a similar kind of "error"

`define('FS_METHOD', 'ssh2');` causes this...

`
Fatal error: Uncaught Error: Call to undefined function ssh2_sftp_realpath() in E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-ssh2.php:305 Stack trace: #0 E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-base.php(248): WP_Filesystem_SSH2->cwd() #1 E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-base.php(227): WP_Filesystem_Base->search_for_folder('/work/projects/...') #2 E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-base.php(73): WP_Filesystem_Base->find_folder('/work/projects/...') #3 E:\work\projects\webdesign\wordpress-themeisle\wp-content\plugins\visualizer\classes\Visualizer\Module.php(474): WP_Filesystem_Base->wp_content_dir() #4 E:\work\projects\webdesign\wordpress-themeisle\wp-content\plugins\visualizer\classes\Visualizer\Module\Frontend.php(181): Visualizer_Module->get_user_customization_js() #5 E:\work\projects\webdesign\wordpress-themeisle\wp-includes\class-wp-ho in E:\work\projects\webdesign\wordpress-themeisle\wp-admin\includes\class-wp-filesystem-ssh2.php on line 305
`
