### ISSUE TITLE
Visualizer (3.4.11) is not compatible with Ninja Forms (3.5.1) and Munk theme

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/visualizer#792]
### Description:
When both Visualizer (3.4.11) is installed and Ninja Forms (3.5.1) is enabled it's not possible to create a new chart or edit an existing chart.

This error can be found in the server error log (with **Ninja Forms plugin and Visualizer only enabled**)
```
[07-Mar-2021 22:04:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_block_editor() on null in /endurableknowledge/wordpress/wp-content/plugins/ninja-forms/blocks/bootstrap.php:97
Stack trace:
#0 /endurableknowledge/wordpress/wp-includes/class-wp-hook.php(287): Ninja_Forms::{closure}()
#1 /endurableknowledge/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /endurableknowledge/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 /endurableknowledge/wordpress/wp-admin/includes/media.php(540): do_action()
#4 /endurableknowledge/wordpress/wp-content/plugins/visualizer/classes/Visualizer/Module/Chart.php(875): wp_iframe()
#5 /endurableknowledge/wordpress/wp-content/plugins/visualizer/classes/Visualizer/Module/Chart.php(593): Visualizer_Module_Chart->_handleTypesPage()
#6 /endurableknowledge/wordpress/wp-includes/class-wp-hook.php(287): Visualizer_Module_Chart->renderChartPages()
#7 /endurableknowledge/wordpress/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#8 /endurableknowledge/wordpress in /endurableknowledge/wordpress/wp-content/plugins/ninja-forms/blocks/bootstrap.php on line 97
```

In the dashboard - only a message about a critical error:
https://vertis.d.pr/3yEoHC

### How to reproduce:
1. Install Visualizer plugin
2. Install Ninja Forms plugin
3. Try to create a new chart

### Expected behaviour:

No errors.

### Current behaviour:

Error shows up

### Reference:

**The same issue happens with Munk theme enabled - https://wordpress.org/themes/munk/**

### Technical info
* WordPress version: 5.6.2
* Plugin version: 3.4.11
* Ninja Forms 3.5.1

Reported here: https://wordpress.org/support/topic/ninja-forms-and-visualizer-cannot-edit-add-chart/

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/1453426992/270824

**Comment by vytisbulkevicius** [comment]
for reference - https://wordpress.org/support/topic/fatal-error-use-markbaker/#post-14235880

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/1486474311/275310/
